{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "3406428b-bcd9-47d6-b712-4a7b2df58000",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "<ref *1> Server {\n",
       "  maxHeaderSize: undefined,\n",
       "  insecureHTTPParser: undefined,\n",
       "  _events: [Object: null prototype] {\n",
       "    request: [Function (anonymous)],\n",
       "    connection: [Function: connectionListener]\n",
       "  },\n",
       "  _eventsCount: 2,\n",
       "  _maxListeners: undefined,\n",
       "  _connections: 0,\n",
       "  _handle: TCP {\n",
       "    reading: false,\n",
       "    onconnection: [Function: onconnection],\n",
       "    [Symbol(owner_symbol)]: [Circular *1],\n",
       "    [Symbol(kResourceStore)]: undefined\n",
       "  },\n",
       "  _usingWorkers: false,\n",
       "  _workers: [],\n",
       "  _unref: false,\n",
       "  allowHalfOpen: true,\n",
       "  pauseOnConnect: false,\n",
       "  noDelay: false,\n",
       "  keepAlive: false,\n",
       "  keepAliveInitialDelay: 0,\n",
       "  httpAllowHalfOpen: false,\n",
       "  timeout: 0,\n",
       "  keepAliveTimeout: 5000,\n",
       "  maxHeadersCount: null,\n",
       "  maxRequestsPerSocket: 0,\n",
       "  headersTimeout: 60000,\n",
       "  requestTimeout: 0,\n",
       "  _connectionKey: '6::::8080',\n",
       "  [Symbol(IncomingMessage)]: [Function: IncomingMessage],\n",
       "  [Symbol(ServerResponse)]: [Function: ServerResponse],\n",
       "  [Symbol(kCapture)]: false,\n",
       "  [Symbol(async_id_symbol)]: 927,\n",
       "  [Symbol(kUniqueHeaders)]: null\n",
       "}"
      ]
     },
     "execution_count": 3,
     "metadata": {},
     "output_type": "execute_result"
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Flushing 0 metrics via HTTP\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Error: [RC] Error in request\n",
      "    at /app/node_modules/dd-trace/packages/dd-trace/src/log/writer.js:69:46\n",
      "    at withNoop (/app/node_modules/dd-trace/packages/dd-trace/src/log/writer.js:21:3)\n",
      "    at onError (/app/node_modules/dd-trace/packages/dd-trace/src/log/writer.js:69:18)\n",
      "    at Channel.publish (node:diagnostics_channel:56:9)\n",
      "    at Object.error (/app/node_modules/dd-trace/packages/dd-trace/src/log/index.js:102:20)\n",
      "    at /app/node_modules/dd-trace/packages/dd-trace/src/appsec/remote_config/manager.js:137:13\n",
      "    at ClientRequest.<anonymous> (/app/node_modules/dd-trace/packages/dd-trace/src/exporters/common/request.js:137:7)\n",
      "    at Object.onceWrapper (node:events:628:26)\n",
      "    at ClientRequest.emit (node:events:513:28)\n",
      "    at ClientRequest.req.emit (/app/node_modules/dd-trace/packages/datadog-instrumentations/src/http/client.js:109:25)\n",
      "Error: connect ECONNREFUSED 127.0.0.1:8126\n",
      "    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16)\n",
      "    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17) {\n",
      "  errno: -111,\n",
      "  code: 'ECONNREFUSED',\n",
      "  syscall: 'connect',\n",
      "  address: '127.0.0.1',\n",
      "  port: 8126\n",
      "}\n",
      "Error: [RC] Error in request\n",
      "    at /app/node_modules/dd-trace/packages/dd-trace/src/log/writer.js:69:46\n",
      "    at withNoop (/app/node_modules/dd-trace/packages/dd-trace/src/log/writer.js:21:3)\n",
      "    at onError (/app/node_modules/dd-trace/packages/dd-trace/src/log/writer.js:69:18)\n",
      "    at Channel.publish (node:diagnostics_channel:56:9)\n",
      "    at Object.error (/app/node_modules/dd-trace/packages/dd-trace/src/log/index.js:102:20)\n",
      "    at /app/node_modules/dd-trace/packages/dd-trace/src/appsec/remote_config/manager.js:137:13\n",
      "    at ClientRequest.<anonymous> (/app/node_modules/dd-trace/packages/dd-trace/src/exporters/common/request.js:137:7)\n",
      "    at Object.onceWrapper (node:events:628:26)\n",
      "    at ClientRequest.emit (node:events:513:28)\n",
      "    at ClientRequest.req.emit (/app/node_modules/dd-trace/packages/datadog-instrumentations/src/http/client.js:109:25)\n",
      "Error: connect ECONNREFUSED 127.0.0.1:8126\n",
      "    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16)\n",
      "    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17) {\n",
      "  errno: -111,\n",
      "  code: 'ECONNREFUSED',\n",
      "  syscall: 'connect',\n",
      "  address: '127.0.0.1',\n",
      "  port: 8126\n",
      "}\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Flushing 0 metrics via HTTP\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Error: [RC] Error in request\n",
      "    at /app/node_modules/dd-trace/packages/dd-trace/src/log/writer.js:69:46\n",
      "    at withNoop (/app/node_modules/dd-trace/packages/dd-trace/src/log/writer.js:21:3)\n",
      "    at onError (/app/node_modules/dd-trace/packages/dd-trace/src/log/writer.js:69:18)\n",
      "    at Channel.publish (node:diagnostics_channel:56:9)\n",
      "    at Object.error (/app/node_modules/dd-trace/packages/dd-trace/src/log/index.js:102:20)\n",
      "    at /app/node_modules/dd-trace/packages/dd-trace/src/appsec/remote_config/manager.js:137:13\n",
      "    at ClientRequest.<anonymous> (/app/node_modules/dd-trace/packages/dd-trace/src/exporters/common/request.js:137:7)\n",
      "    at Object.onceWrapper (node:events:628:26)\n",
      "    at ClientRequest.emit (node:events:513:28)\n",
      "    at ClientRequest.req.emit (/app/node_modules/dd-trace/packages/datadog-instrumentations/src/http/client.js:109:25)\n",
      "Error: connect ECONNREFUSED 127.0.0.1:8126\n",
      "    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16)\n",
      "    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17) {\n",
      "  errno: -111,\n",
      "  code: 'ECONNREFUSED',\n",
      "  syscall: 'connect',\n",
      "  address: '127.0.0.1',\n",
      "  port: 8126\n",
      "}\n",
      "Error: [RC] Error in request\n",
      "    at /app/node_modules/dd-trace/packages/dd-trace/src/log/writer.js:69:46\n",
      "    at withNoop (/app/node_modules/dd-trace/packages/dd-trace/src/log/writer.js:21:3)\n",
      "    at onError (/app/node_modules/dd-trace/packages/dd-trace/src/log/writer.js:69:18)\n",
      "    at Channel.publish (node:diagnostics_channel:56:9)\n",
      "    at Object.error (/app/node_modules/dd-trace/packages/dd-trace/src/log/index.js:102:20)\n",
      "    at /app/node_modules/dd-trace/packages/dd-trace/src/appsec/remote_config/manager.js:137:13\n",
      "    at ClientRequest.<anonymous> (/app/node_modules/dd-trace/packages/dd-trace/src/exporters/common/request.js:137:7)\n",
      "    at Object.onceWrapper (node:events:628:26)\n",
      "    at ClientRequest.emit (node:events:513:28)\n",
      "    at ClientRequest.req.emit (/app/node_modules/dd-trace/packages/datadog-instrumentations/src/http/client.js:109:25)\n",
      "Error: connect ECONNREFUSED 127.0.0.1:8126\n",
      "    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16)\n",
      "    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17) {\n",
      "  errno: -111,\n",
      "  code: 'ECONNREFUSED',\n",
      "  syscall: 'connect',\n",
      "  address: '127.0.0.1',\n",
      "  port: 8126\n",
      "}\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Flushing 0 metrics via HTTP\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Error: [RC] Error in request\n",
      "    at /app/node_modules/dd-trace/packages/dd-trace/src/log/writer.js:69:46\n",
      "    at withNoop (/app/node_modules/dd-trace/packages/dd-trace/src/log/writer.js:21:3)\n",
      "    at onError (/app/node_modules/dd-trace/packages/dd-trace/src/log/writer.js:69:18)\n",
      "    at Channel.publish (node:diagnostics_channel:56:9)\n",
      "    at Object.error (/app/node_modules/dd-trace/packages/dd-trace/src/log/index.js:102:20)\n",
      "    at /app/node_modules/dd-trace/packages/dd-trace/src/appsec/remote_config/manager.js:137:13\n",
      "    at ClientRequest.<anonymous> (/app/node_modules/dd-trace/packages/dd-trace/src/exporters/common/request.js:137:7)\n",
      "    at Object.onceWrapper (node:events:628:26)\n",
      "    at ClientRequest.emit (node:events:513:28)\n",
      "    at ClientRequest.req.emit (/app/node_modules/dd-trace/packages/datadog-instrumentations/src/http/client.js:109:25)\n",
      "Error: connect ECONNREFUSED 127.0.0.1:8126\n",
      "    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16)\n",
      "    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17) {\n",
      "  errno: -111,\n",
      "  code: 'ECONNREFUSED',\n",
      "  syscall: 'connect',\n",
      "  address: '127.0.0.1',\n",
      "  port: 8126\n",
      "}\n",
      "Error: [RC] Error in request\n",
      "    at /app/node_modules/dd-trace/packages/dd-trace/src/log/writer.js:69:46\n",
      "    at withNoop (/app/node_modules/dd-trace/packages/dd-trace/src/log/writer.js:21:3)\n",
      "    at onError (/app/node_modules/dd-trace/packages/dd-trace/src/log/writer.js:69:18)\n",
      "    at Channel.publish (node:diagnostics_channel:56:9)\n",
      "    at Object.error (/app/node_modules/dd-trace/packages/dd-trace/src/log/index.js:102:20)\n",
      "    at /app/node_modules/dd-trace/packages/dd-trace/src/appsec/remote_config/manager.js:137:13\n",
      "    at ClientRequest.<anonymous> (/app/node_modules/dd-trace/packages/dd-trace/src/exporters/common/request.js:137:7)\n",
      "    at Object.onceWrapper (node:events:628:26)\n",
      "    at ClientRequest.emit (node:events:513:28)\n",
      "    at ClientRequest.req.emit (/app/node_modules/dd-trace/packages/datadog-instrumentations/src/http/client.js:109:25)\n",
      "Error: connect ECONNREFUSED 127.0.0.1:8126\n",
      "    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16)\n",
      "    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17) {\n",
      "  errno: -111,\n",
      "  code: 'ECONNREFUSED',\n",
      "  syscall: 'connect',\n",
      "  address: '127.0.0.1',\n",
      "  port: 8126\n",
      "}\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Flushing 0 metrics via HTTP\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Error: Error sending telemetry data null\n",
      "    at /app/node_modules/dd-trace/packages/dd-trace/src/log/writer.js:69:46\n",
      "    at withNoop (/app/node_modules/dd-trace/packages/dd-trace/src/log/writer.js:21:3)\n",
      "    at onError (/app/node_modules/dd-trace/packages/dd-trace/src/log/writer.js:69:18)\n",
      "    at Channel.publish (node:diagnostics_channel:56:9)\n",
      "    at Object.error (/app/node_modules/dd-trace/packages/dd-trace/src/log/index.js:102:20)\n",
      "    at /app/node_modules/dd-trace/packages/dd-trace/src/telemetry/send-data.js:103:56\n",
      "    at IncomingMessage.<anonymous> (/app/node_modules/dd-trace/packages/dd-trace/src/exporters/common/request.js:96:11)\n",
      "    at IncomingMessage.emit (node:events:525:35)\n",
      "    at endReadableNT (node:internal/streams/readable:1358:12)\n",
      "    at processTicksAndRejections (node:internal/process/task_queues:83:21)\n",
      "Error: Error sending telemetry data null\n",
      "    at /app/node_modules/dd-trace/packages/dd-trace/src/log/writer.js:69:46\n",
      "    at withNoop (/app/node_modules/dd-trace/packages/dd-trace/src/log/writer.js:21:3)\n",
      "    at onError (/app/node_modules/dd-trace/packages/dd-trace/src/log/writer.js:69:18)\n",
      "    at Channel.publish (node:diagnostics_channel:56:9)\n",
      "    at Object.error (/app/node_modules/dd-trace/packages/dd-trace/src/log/index.js:102:20)\n",
      "    at /app/node_modules/dd-trace/packages/dd-trace/src/telemetry/send-data.js:103:56\n",
      "    at IncomingMessage.<anonymous> (/app/node_modules/dd-trace/packages/dd-trace/src/exporters/common/request.js:96:11)\n",
      "    at IncomingMessage.emit (node:events:525:35)\n",
      "    at endReadableNT (node:internal/streams/readable:1358:12)\n",
      "    at processTicksAndRejections (node:internal/process/task_queues:83:21)\n",
      "Error: [RC] Error in request\n",
      "    at /app/node_modules/dd-trace/packages/dd-trace/src/log/writer.js:69:46\n",
      "    at withNoop (/app/node_modules/dd-trace/packages/dd-trace/src/log/writer.js:21:3)\n",
      "    at onError (/app/node_modules/dd-trace/packages/dd-trace/src/log/writer.js:69:18)\n",
      "    at Channel.publish (node:diagnostics_channel:56:9)\n",
      "    at Object.error (/app/node_modules/dd-trace/packages/dd-trace/src/log/index.js:102:20)\n",
      "    at /app/node_modules/dd-trace/packages/dd-trace/src/appsec/remote_config/manager.js:137:13\n",
      "    at ClientRequest.<anonymous> (/app/node_modules/dd-trace/packages/dd-trace/src/exporters/common/request.js:137:7)\n",
      "    at Object.onceWrapper (node:events:628:26)\n",
      "    at ClientRequest.emit (node:events:513:28)\n",
      "    at ClientRequest.req.emit (/app/node_modules/dd-trace/packages/datadog-instrumentations/src/http/client.js:109:25)\n",
      "Error: connect ECONNREFUSED 127.0.0.1:8126\n",
      "    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16)\n",
      "    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17) {\n",
      "  errno: -111,\n",
      "  code: 'ECONNREFUSED',\n",
      "  syscall: 'connect',\n",
      "  address: '127.0.0.1',\n",
      "  port: 8126\n",
      "}\n",
      "Error: [RC] Error in request\n",
      "    at /app/node_modules/dd-trace/packages/dd-trace/src/log/writer.js:69:46\n",
      "    at withNoop (/app/node_modules/dd-trace/packages/dd-trace/src/log/writer.js:21:3)\n",
      "    at onError (/app/node_modules/dd-trace/packages/dd-trace/src/log/writer.js:69:18)\n",
      "    at Channel.publish (node:diagnostics_channel:56:9)\n",
      "    at Object.error (/app/node_modules/dd-trace/packages/dd-trace/src/log/index.js:102:20)\n",
      "    at /app/node_modules/dd-trace/packages/dd-trace/src/appsec/remote_config/manager.js:137:13\n",
      "    at ClientRequest.<anonymous> (/app/node_modules/dd-trace/packages/dd-trace/src/exporters/common/request.js:137:7)\n",
      "    at Object.onceWrapper (node:events:628:26)\n",
      "    at ClientRequest.emit (node:events:513:28)\n",
      "    at ClientRequest.req.emit (/app/node_modules/dd-trace/packages/datadog-instrumentations/src/http/client.js:109:25)\n",
      "Error: connect ECONNREFUSED 127.0.0.1:8126\n",
      "    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16)\n",
      "    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17) {\n",
      "  errno: -111,\n",
      "  code: 'ECONNREFUSED',\n",
      "  syscall: 'connect',\n",
      "  address: '127.0.0.1',\n",
      "  port: 8126\n",
      "}\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Flushing 0 metrics via HTTP\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Error: [RC] Error in request\n",
      "    at /app/node_modules/dd-trace/packages/dd-trace/src/log/writer.js:69:46\n",
      "    at withNoop (/app/node_modules/dd-trace/packages/dd-trace/src/log/writer.js:21:3)\n",
      "    at onError (/app/node_modules/dd-trace/packages/dd-trace/src/log/writer.js:69:18)\n",
      "    at Channel.publish (node:diagnostics_channel:56:9)\n",
      "    at Object.error (/app/node_modules/dd-trace/packages/dd-trace/src/log/index.js:102:20)\n",
      "    at /app/node_modules/dd-trace/packages/dd-trace/src/appsec/remote_config/manager.js:137:13\n",
      "    at ClientRequest.<anonymous> (/app/node_modules/dd-trace/packages/dd-trace/src/exporters/common/request.js:137:7)\n",
      "    at Object.onceWrapper (node:events:628:26)\n",
      "    at ClientRequest.emit (node:events:513:28)\n",
      "    at ClientRequest.req.emit (/app/node_modules/dd-trace/packages/datadog-instrumentations/src/http/client.js:109:25)\n",
      "Error: connect ECONNREFUSED 127.0.0.1:8126\n",
      "    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16)\n",
      "    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17) {\n",
      "  errno: -111,\n",
      "  code: 'ECONNREFUSED',\n",
      "  syscall: 'connect',\n",
      "  address: '127.0.0.1',\n",
      "  port: 8126\n",
      "}\n",
      "Error: [RC] Error in request\n",
      "    at /app/node_modules/dd-trace/packages/dd-trace/src/log/writer.js:69:46\n",
      "    at withNoop (/app/node_modules/dd-trace/packages/dd-trace/src/log/writer.js:21:3)\n",
      "    at onError (/app/node_modules/dd-trace/packages/dd-trace/src/log/writer.js:69:18)\n",
      "    at Channel.publish (node:diagnostics_channel:56:9)\n",
      "    at Object.error (/app/node_modules/dd-trace/packages/dd-trace/src/log/index.js:102:20)\n",
      "    at /app/node_modules/dd-trace/packages/dd-trace/src/appsec/remote_config/manager.js:137:13\n",
      "    at ClientRequest.<anonymous> (/app/node_modules/dd-trace/packages/dd-trace/src/exporters/common/request.js:137:7)\n",
      "    at Object.onceWrapper (node:events:628:26)\n",
      "    at ClientRequest.emit (node:events:513:28)\n",
      "    at ClientRequest.req.emit (/app/node_modules/dd-trace/packages/datadog-instrumentations/src/http/client.js:109:25)\n",
      "Error: connect ECONNREFUSED 127.0.0.1:8126\n",
      "    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16)\n",
      "    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17) {\n",
      "  errno: -111,\n",
      "  code: 'ECONNREFUSED',\n",
      "  syscall: 'connect',\n",
      "  address: '127.0.0.1',\n",
      "  port: 8126\n",
      "}\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Flushing 0 metrics via HTTP\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Error: [RC] Error in request\n",
      "    at /app/node_modules/dd-trace/packages/dd-trace/src/log/writer.js:69:46\n",
      "    at withNoop (/app/node_modules/dd-trace/packages/dd-trace/src/log/writer.js:21:3)\n",
      "    at onError (/app/node_modules/dd-trace/packages/dd-trace/src/log/writer.js:69:18)\n",
      "    at Channel.publish (node:diagnostics_channel:56:9)\n",
      "    at Object.error (/app/node_modules/dd-trace/packages/dd-trace/src/log/index.js:102:20)\n",
      "    at /app/node_modules/dd-trace/packages/dd-trace/src/appsec/remote_config/manager.js:137:13\n",
      "    at ClientRequest.<anonymous> (/app/node_modules/dd-trace/packages/dd-trace/src/exporters/common/request.js:137:7)\n",
      "    at Object.onceWrapper (node:events:628:26)\n",
      "    at ClientRequest.emit (node:events:513:28)\n",
      "    at ClientRequest.req.emit (/app/node_modules/dd-trace/packages/datadog-instrumentations/src/http/client.js:109:25)\n",
      "Error: connect ECONNREFUSED 127.0.0.1:8126\n",
      "    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16)\n",
      "    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17) {\n",
      "  errno: -111,\n",
      "  code: 'ECONNREFUSED',\n",
      "  syscall: 'connect',\n",
      "  address: '127.0.0.1',\n",
      "  port: 8126\n",
      "}\n",
      "Error: [RC] Error in request\n",
      "    at /app/node_modules/dd-trace/packages/dd-trace/src/log/writer.js:69:46\n",
      "    at withNoop (/app/node_modules/dd-trace/packages/dd-trace/src/log/writer.js:21:3)\n",
      "    at onError (/app/node_modules/dd-trace/packages/dd-trace/src/log/writer.js:69:18)\n",
      "    at Channel.publish (node:diagnostics_channel:56:9)\n",
      "    at Object.error (/app/node_modules/dd-trace/packages/dd-trace/src/log/index.js:102:20)\n",
      "    at /app/node_modules/dd-trace/packages/dd-trace/src/appsec/remote_config/manager.js:137:13\n",
      "    at ClientRequest.<anonymous> (/app/node_modules/dd-trace/packages/dd-trace/src/exporters/common/request.js:137:7)\n",
      "    at Object.onceWrapper (node:events:628:26)\n",
      "    at ClientRequest.emit (node:events:513:28)\n",
      "    at ClientRequest.req.emit (/app/node_modules/dd-trace/packages/datadog-instrumentations/src/http/client.js:109:25)\n",
      "Error: connect ECONNREFUSED 127.0.0.1:8126\n",
      "    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16)\n",
      "    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17) {\n",
      "  errno: -111,\n",
      "  code: 'ECONNREFUSED',\n",
      "  syscall: 'connect',\n",
      "  address: '127.0.0.1',\n",
      "  port: 8126\n",
      "}\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Flushing 0 metrics via HTTP\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Error: [RC] Error in request\n",
      "    at /app/node_modules/dd-trace/packages/dd-trace/src/log/writer.js:69:46\n",
      "    at withNoop (/app/node_modules/dd-trace/packages/dd-trace/src/log/writer.js:21:3)\n",
      "    at onError (/app/node_modules/dd-trace/packages/dd-trace/src/log/writer.js:69:18)\n",
      "    at Channel.publish (node:diagnostics_channel:56:9)\n",
      "    at Object.error (/app/node_modules/dd-trace/packages/dd-trace/src/log/index.js:102:20)\n",
      "    at /app/node_modules/dd-trace/packages/dd-trace/src/appsec/remote_config/manager.js:137:13\n",
      "    at ClientRequest.<anonymous> (/app/node_modules/dd-trace/packages/dd-trace/src/exporters/common/request.js:137:7)\n",
      "    at Object.onceWrapper (node:events:628:26)\n",
      "    at ClientRequest.emit (node:events:513:28)\n",
      "    at ClientRequest.req.emit (/app/node_modules/dd-trace/packages/datadog-instrumentations/src/http/client.js:109:25)\n",
      "Error: connect ECONNREFUSED 127.0.0.1:8126\n",
      "    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16)\n",
      "    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17) {\n",
      "  errno: -111,\n",
      "  code: 'ECONNREFUSED',\n",
      "  syscall: 'connect',\n",
      "  address: '127.0.0.1',\n",
      "  port: 8126\n",
      "}\n",
      "Error: [RC] Error in request\n",
      "    at /app/node_modules/dd-trace/packages/dd-trace/src/log/writer.js:69:46\n",
      "    at withNoop (/app/node_modules/dd-trace/packages/dd-trace/src/log/writer.js:21:3)\n",
      "    at onError (/app/node_modules/dd-trace/packages/dd-trace/src/log/writer.js:69:18)\n",
      "    at Channel.publish (node:diagnostics_channel:56:9)\n",
      "    at Object.error (/app/node_modules/dd-trace/packages/dd-trace/src/log/index.js:102:20)\n",
      "    at /app/node_modules/dd-trace/packages/dd-trace/src/appsec/remote_config/manager.js:137:13\n",
      "    at ClientRequest.<anonymous> (/app/node_modules/dd-trace/packages/dd-trace/src/exporters/common/request.js:137:7)\n",
      "    at Object.onceWrapper (node:events:628:26)\n",
      "    at ClientRequest.emit (node:events:513:28)\n",
      "    at ClientRequest.req.emit (/app/node_modules/dd-trace/packages/datadog-instrumentations/src/http/client.js:109:25)\n",
      "Error: connect ECONNREFUSED 127.0.0.1:8126\n",
      "    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16)\n",
      "    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17) {\n",
      "  errno: -111,\n",
      "  code: 'ECONNREFUSED',\n",
      "  syscall: 'connect',\n",
      "  address: '127.0.0.1',\n",
      "  port: 8126\n",
      "}\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Flushing 0 metrics via HTTP\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Error: [RC] Error in request\n",
      "    at /app/node_modules/dd-trace/packages/dd-trace/src/log/writer.js:69:46\n",
      "    at withNoop (/app/node_modules/dd-trace/packages/dd-trace/src/log/writer.js:21:3)\n",
      "    at onError (/app/node_modules/dd-trace/packages/dd-trace/src/log/writer.js:69:18)\n",
      "    at Channel.publish (node:diagnostics_channel:56:9)\n",
      "    at Object.error (/app/node_modules/dd-trace/packages/dd-trace/src/log/index.js:102:20)\n",
      "    at /app/node_modules/dd-trace/packages/dd-trace/src/appsec/remote_config/manager.js:137:13\n",
      "    at ClientRequest.<anonymous> (/app/node_modules/dd-trace/packages/dd-trace/src/exporters/common/request.js:137:7)\n",
      "    at Object.onceWrapper (node:events:628:26)\n",
      "    at ClientRequest.emit (node:events:513:28)\n",
      "    at ClientRequest.req.emit (/app/node_modules/dd-trace/packages/datadog-instrumentations/src/http/client.js:109:25)\n",
      "Error: connect ECONNREFUSED 127.0.0.1:8126\n",
      "    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16)\n",
      "    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17) {\n",
      "  errno: -111,\n",
      "  code: 'ECONNREFUSED',\n",
      "  syscall: 'connect',\n",
      "  address: '127.0.0.1',\n",
      "  port: 8126\n",
      "}\n",
      "Error: [RC] Error in request\n",
      "    at /app/node_modules/dd-trace/packages/dd-trace/src/log/writer.js:69:46\n",
      "    at withNoop (/app/node_modules/dd-trace/packages/dd-trace/src/log/writer.js:21:3)\n",
      "    at onError (/app/node_modules/dd-trace/packages/dd-trace/src/log/writer.js:69:18)\n",
      "    at Channel.publish (node:diagnostics_channel:56:9)\n",
      "    at Object.error (/app/node_modules/dd-trace/packages/dd-trace/src/log/index.js:102:20)\n",
      "    at /app/node_modules/dd-trace/packages/dd-trace/src/appsec/remote_config/manager.js:137:13\n",
      "    at ClientRequest.<anonymous> (/app/node_modules/dd-trace/packages/dd-trace/src/exporters/common/request.js:137:7)\n",
      "    at Object.onceWrapper (node:events:628:26)\n",
      "    at ClientRequest.emit (node:events:513:28)\n",
      "    at ClientRequest.req.emit (/app/node_modules/dd-trace/packages/datadog-instrumentations/src/http/client.js:109:25)\n",
      "Error: connect ECONNREFUSED 127.0.0.1:8126\n",
      "    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16)\n",
      "    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17) {\n",
      "  errno: -111,\n",
      "  code: 'ECONNREFUSED',\n",
      "  syscall: 'connect',\n",
      "  address: '127.0.0.1',\n",
      "  port: 8126\n",
      "}\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Flushing 0 metrics via HTTP\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Error: [RC] Error in request\n",
      "    at /app/node_modules/dd-trace/packages/dd-trace/src/log/writer.js:69:46\n",
      "    at withNoop (/app/node_modules/dd-trace/packages/dd-trace/src/log/writer.js:21:3)\n",
      "    at onError (/app/node_modules/dd-trace/packages/dd-trace/src/log/writer.js:69:18)\n",
      "    at Channel.publish (node:diagnostics_channel:56:9)\n",
      "    at Object.error (/app/node_modules/dd-trace/packages/dd-trace/src/log/index.js:102:20)\n",
      "    at /app/node_modules/dd-trace/packages/dd-trace/src/appsec/remote_config/manager.js:137:13\n",
      "    at ClientRequest.<anonymous> (/app/node_modules/dd-trace/packages/dd-trace/src/exporters/common/request.js:137:7)\n",
      "    at Object.onceWrapper (node:events:628:26)\n",
      "    at ClientRequest.emit (node:events:513:28)\n",
      "    at ClientRequest.req.emit (/app/node_modules/dd-trace/packages/datadog-instrumentations/src/http/client.js:109:25)\n",
      "Error: connect ECONNREFUSED 127.0.0.1:8126\n",
      "    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16)\n",
      "    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17) {\n",
      "  errno: -111,\n",
      "  code: 'ECONNREFUSED',\n",
      "  syscall: 'connect',\n",
      "  address: '127.0.0.1',\n",
      "  port: 8126\n",
      "}\n"
     ]
    }
   ],
   "source": [
    "var http = require('http');\n",
    "\n",
    "http.createServer(function (req, res) {\n",
    "  res.writeHead(200, {'Content-Type': 'text/html'});\n",
    "  res.end('Hello World!');\n",
    "}).listen(8080);"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "474d2a17-c413-42c4-96b5-70da492d3eda",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "JavaScript (Node.js)",
   "language": "javascript",
   "name": "javascript"
  },
  "language_info": {
   "file_extension": ".js",
   "mimetype": "application/javascript",
   "name": "javascript",
   "version": "16.20.2"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
